INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (101, 'Shrunal', 'LEARN AWS', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (103, 'Shrunal', 'KUBERNETES', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (102, 'Shrunal', 'DOCKER', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (1031, 'Adam', 'Learn Spring', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (1021, 'Adam', 'Learn Spring Boot', CURRENT_DATE(), false);