INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (101, 'Shrunal', 'AWS CERTIFIED', CURRENT_DATE, false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (103, 'Shrunal', 'AWS 1', CURRENT_DATE, false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES (102, 'Shrunal', 'AWS 2', CURRENT_DATE, false);